-- Add new columns to spaces table for technical configuration

ALTER TABLE spaces ADD COLUMN IF NOT EXISTS width NUMERIC;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS length NUMERIC;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS height NUMERIC;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS area_m2 NUMERIC;

ALTER TABLE spaces ADD COLUMN IF NOT EXISTS light_type TEXT;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS light_brand_model TEXT;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS light_watts NUMERIC;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS light_ppfd NUMERIC;

ALTER TABLE spaces ADD COLUMN IF NOT EXISTS vent_extraction NUMERIC;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS vent_intraction NUMERIC;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS vent_filter_brand TEXT;
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS vent_extra_equipment TEXT;

ALTER TABLE spaces ADD COLUMN IF NOT EXISTS pot_capacity INTEGER;
